### ISSUE TITLE
FEATURE: DevOps, azurerm_static_site.ui is deprecated

### ISSUE THREAD

**Issue by andriikaplanovskyi** [onebeyond/onebeyond-studio-obelisk-fe-vuetify#57]
![image](https://github.com/onebeyond/onebeyond-studio-obelisk-fe-vuetify/assets/120190898/aec6fe52-0552-4c1b-91ab-52e1e4c4fbf7)

**Comment by nickskliar-davies** [comment]
Fixed

https://github.com/onebeyond/onebeyond-studio-obelisk-fe-vuetify/commit/b25eb8bc1d2a0a16e11cca25d9691a0a7a82db69
